<?php
$date = $_POST['date'];
$DB = new mysqli('localhost', 'root', '', 'tc-db-log');
$htmltable = '<tr>';
$htmltable .= '<th style="display:none"></th>';
$htmltable .= '<th></th>';
$htmltable .= '<th></th>';
$htmltable .= '<th colspan="2">07:30 - 08:00</th>';
$htmltable .= '<th colspan="2">08:00 - 08:30</th>';
$htmltable .= '<th colspan="2">08:30 - 09:00</th>';
$htmltable .= '<th colspan="2">09:00 - 09:30</th>';
$htmltable .= '<th colspan="2">09:30 - 10:00</th>';
$htmltable .= '<th colspan="2">15:00 - 15:30</th>';
$htmltable .= '<th colspan="2">15:30 - 16:00</th>';
$htmltable .= '<th colspan="2">16:00 - 16:30</th>';
$htmltable .= '<th colspan="2">16:30 - 17:00</th>';
$htmltable .= '<th colspan="2">17:00 - 17:30</th>';
$htmltable .= '<th colspan="2">17:30 - 18:00</th>';
$htmltable .= '<th colspan="2">18:00 - 18:30</th>';
$htmltable .= '<th colspan="2">18:30 - 19:00</th>';
$htmltable .= '<th colspan="2">19:00 - 19:30</th>';
$htmltable .= '<th colspan="2">19:30 - 20:00</th>';
$htmltable .= '</tr>';
$htmltable .= '<tr>';
$htmltable .= '<th style="display:none">LogDate</th>';
$htmltable .= '<th>Объект КОР</th>';
$htmltable .= '<th>Исполнитель</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '<th>ВХ</th>';
$htmltable .= '<th>ВЫХ</th>';
$htmltable .= '</tr>';
$htmltable .= '<tr style="display:none">';
$htmltable .= '<td style="display:none"></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '</tr>';
$v_for_excel_in_out = $DB->query("SELECT * FROM `v_for_excel_in_out` WHERE `logDATE` = '$date' ORDER BY `logDATE`, `obj`, `org`;");
while ($row = $v_for_excel_in_out->fetch_row()) {
    $htmltable .= '<tr>';
    if ($row[4] == 'ВХОД') {
        $htmltable .= "<td style='display:none'>{$row[1]}</td>";
        $htmltable .= "<td>{$row[3]}</td>";
        $htmltable .= "<td>{$row[2]}</td>";
        $htmltable .= "<td>{$row[5]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[6]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[7]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[8]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[9]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[10]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[11]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[12]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[13]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[14]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[15]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[16]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[17]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[18]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[19]}</td>";
        $htmltable .= "<td></td>";
    } else {
        $htmltable .= "<td style='display:none'>{$row[1]}</td>";
        $htmltable .= "<td>{$row[3]}</td>";
        $htmltable .= "<td>{$row[2]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[5]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[6]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[7]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[8]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[9]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[10]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[11]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[12]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[13]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[14]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[15]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[16]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[17]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[18]}</td>";
        $htmltable .= "<td></td>";
        $htmltable .= "<td>{$row[19]}</td>";
    }
    $htmltable .= '</tr>';
}
$htmltable .= '<tr>';
$htmltable .= '<td style="display:none"></td>';
$htmltable .= '<td colspan="2">Общий итог</td>';
$htmltable .= '<td style="display:none"></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '<td></td>';
$htmltable .= '</tr>';
mysqli_close($DB);
exit($htmltable);
